project_id = "nwgljkjckcizbrpbqsro"

[functions.firecrawl-profile]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-crawl]
verify_jwt = false

[functions.firecrawl-school-logo]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.cfbd-api]
verify_jwt = false