/**
 * generate-tab-inventory.ts — Pass 6.1
 *
 * VERIFIES: docs/architecture/athlete-lab-tab-inventory.md (machine block)
 * RECIPE:
 *   deno run --allow-read --allow-write scripts/generate-tab-inventory.ts
 *   (or:  npx tsx scripts/generate-tab-inventory.ts)
 *   Reads:  src/features/athlete-lab/components/NodeEditor.tsx
 *   Writes: docs/architecture/athlete-lab-tab-inventory.md (between
 *           <!-- INVENTORY:AUTO:START --> and <!-- INVENTORY:AUTO:END --> markers)
 *   Exit codes: 0 ok, 2 parse failure, 3 marker missing, 4 inventory drift
 *               in --check mode (no write).
 * BACKLINKS:
 *   - docs/risk-register/F-SLICE-E-3-recipe-propagation-without-independent-verification-process-lesson-no-severity.md
 *   - docs/risk-register/R-05-tab-consolidation-hides-existing-draft-state-content-from-admins.md
 *   - docs/risk-register/R-12-mechanics-tab-deletion-strands-knowledge-base-sub-sections-keyed-to-mechanics.md
 *
 * Boundary policy:
 *   - DERIVABLE  (regenerated):  tab order, internal key, display label,
 *                                advanced flag, hidden flag, summary table
 *                                rows, source-line citation.
 *   - JUDGMENT   (preserved):    per-tab "Description", "Fields/sections",
 *                                "Disposition (1c.3 prediction)" prose lives
 *                                outside the AUTO block and is never touched.
 *
 * If the TABS array shape changes (e.g. fields added), update this script
 * BEFORE the next regen — silent shape drift is the F-SLICE-E-3 failure mode.
 */

import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "src/features/athlete-lab/components/NodeEditor.tsx";
const TARGET = "docs/architecture/athlete-lab-tab-inventory.md";
const START = "<!-- INVENTORY:AUTO:START -->";
const END = "<!-- INVENTORY:AUTO:END -->";

type TabRow = {
  key: string;
  label: string;
  hidden: boolean;        // commented out in TABS array
  advanced: boolean;      // present in ADVANCED_TAB_KEYS
};

function parseTabs(src: string): { rows: TabRow[]; tabsStartLine: number; tabsEndLine: number } {
  const lines = src.split("\n");
  const tabsStart = lines.findIndex((l) => /^const TABS:/.test(l));
  if (tabsStart < 0) {
    console.error("[generate-tab-inventory] could not find `const TABS:` declaration");
    process.exit(2);
  }
  // find closing `];`
  let tabsEnd = -1;
  for (let i = tabsStart; i < lines.length; i++) {
    if (/^\];\s*$/.test(lines[i])) { tabsEnd = i; break; }
  }
  if (tabsEnd < 0) {
    console.error("[generate-tab-inventory] could not find closing `];` for TABS");
    process.exit(2);
  }

  // Match lines like: { key: "basics", label: "Basics", icon: "edit", subtitle: "..." },
  // OR commented variants:  // { key: "mechanics", label: "Mechanics", ... },
  const ROW_RE = /(\/\/\s*)?\{\s*key:\s*"([^"]+)"\s*,\s*label:\s*"([^"]+)"/;
  const rows: TabRow[] = [];
  for (let i = tabsStart + 1; i < tabsEnd; i++) {
    const m = ROW_RE.exec(lines[i]);
    if (!m) continue;
    rows.push({
      key: m[2],
      label: m[3],
      hidden: Boolean(m[1]),
      advanced: false, // patched below
    });
  }

  // Locate ADVANCED_TAB_KEYS
  const advLine = lines.find((l) => /ADVANCED_TAB_KEYS:\s*TabKey\[\]/.test(l));
  if (advLine) {
    const advRe = /"([^"]+)"/g;
    const adv = new Set<string>();
    let mm: RegExpExecArray | null;
    while ((mm = advRe.exec(advLine)) !== null) adv.add(mm[1]);
    for (const r of rows) r.advanced = adv.has(r.key);
  }

  return { rows, tabsStartLine: tabsStart + 1, tabsEndLine: tabsEnd + 1 };
}

function renderBlock(rows: TabRow[], srcStart: number, srcEnd: number): string {
  const visible = rows.filter((r) => !r.hidden);
  const hidden = rows.filter((r) => r.hidden);

  const tableRows = rows
    .map((r, i) => {
      const labelCell = r.hidden ? `${r.label} *(hidden)*` : r.label;
      const advCell = r.advanced ? "✓" : "—";
      return `| ${i + 1} | ${labelCell} | \`${r.key}\` | ${advCell} |`;
    })
    .join("\n");

  return [
    START,
    `<!-- Generated by scripts/generate-tab-inventory.ts.`,
    `     Source: ${SOURCE} (TABS array, lines ${srcStart}–${srcEnd}).`,
    `     Edit prose sections above, NOT this block. Run the script to refresh.`,
    `     No date stamp here on purpose — it would break --check determinism. -->`,
    "",
    `**Auto-derived snapshot** — ${rows.length} TABS entries (${visible.length} visible, ${hidden.length} hidden).`,
    "",
    "| # | Tab | Internal key | Advanced? |",
    "|---|---|---|---|",
    tableRows,
    "",
    "**Hidden tabs (commented out in TABS array):**",
    hidden.length === 0
      ? "_none_"
      : hidden.map((r) => `- \`${r.key}\` (${r.label})`).join("\n"),
    "",
    "**Advanced-only tabs (gated by Show Advanced Tabs toggle):**",
    rows
      .filter((r) => r.advanced)
      .map((r) => `- \`${r.key}\` (${r.label})`)
      .join("\n") || "_none_",
    "",
    END,
  ].join("\n");
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const src = readFileSync(SOURCE, "utf8");
  const { rows, tabsStartLine, tabsEndLine } = parseTabs(src);

  if (rows.length === 0) {
    console.error("[generate-tab-inventory] parsed 0 rows — refusing to write");
    process.exit(2);
  }

  const target = readFileSync(TARGET, "utf8");
  const startIdx = target.indexOf(START);
  const endIdx = target.indexOf(END);

  const newBlock = renderBlock(rows, tabsStartLine, tabsEndLine);

  let next: string;
  if (startIdx < 0 || endIdx < 0) {
    if (checkOnly) {
      console.error(`[generate-tab-inventory] AUTO markers missing in ${TARGET}`);
      process.exit(3);
    }
    // Append at end with a separator
    next = target.trimEnd() + "\n\n---\n\n" + newBlock + "\n";
    console.log(`[generate-tab-inventory] markers not found — appended fresh block to ${TARGET}`);
  } else {
    next = target.slice(0, startIdx) + newBlock + target.slice(endIdx + END.length);
  }

  if (checkOnly) {
    if (next !== target) {
      console.error("[generate-tab-inventory] inventory is OUT OF DATE — run without --check to refresh");
      process.exit(4);
    }
    console.log("[generate-tab-inventory] inventory up to date");
    return;
  }

  if (next === target) {
    console.log(`[generate-tab-inventory] no changes (${rows.length} tabs, ${rows.filter((r) => r.hidden).length} hidden)`);
    return;
  }
  writeFileSync(TARGET, next);
  console.log(`[generate-tab-inventory] wrote ${TARGET} (${rows.length} tabs, ${rows.filter((r) => r.hidden).length} hidden)`);
}

main();
