
CREATE TABLE public.admin_tab_guidance (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  tab_key text NOT NULL UNIQUE,
  content text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.admin_tab_guidance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to admin_tab_guidance"
ON public.admin_tab_guidance
FOR ALL
TO public
USING (true)
WITH CHECK (true);

CREATE TRIGGER update_admin_tab_guidance_updated_at
BEFORE UPDATE ON public.admin_tab_guidance
FOR EACH ROW
EXECUTE FUNCTION public.update_athlete_lab_nodes_updated_at();

-- Seed default guidance for all tabs
INSERT INTO public.admin_tab_guidance (tab_key, content) VALUES
('mechanics', '<h3><strong>How to Write Phase-Specific Mechanics Notes (Best Practices + Real Examples)</strong></h3><h4>Why this matters for the AI</h4><p>Breaking the skill into clear phases lets the AI analyze the athlete''s video phase-by-phase, compare it to your elite benchmarks, and give feedback that feels like a top position coach — not generic advice. The more precise and vivid your notes, the more specific and useful the AI feedback becomes.</p><h4>Best practices for writing great mechanics notes</h4><ul><li>Be specific and actionable — use coaching cues, body positions, timing, and feel.</li><li>Include what elite looks like and what common mistakes look like.</li><li>Write in coach voice (short, direct, motivational).</li><li>Reference key body parts the AI can actually see via keypoints (hips, shoulders, feet, head, hands).</li><li>Keep each phase focused — don''t mix phases.</li><li>Use real pro examples when possible.</li></ul><h4>Real examples for "Slant Route" (copy and adapt these)</h4><p><strong>Release Phase (first 1–3 steps off the line)</strong></p><p>"Explosive first step with low pad level. Attack the outside shoulder of the DB to create immediate leverage. Sell vertical hard — shoulders square, eyes downfield. No false steps. Drive through the inside leg with full speed off the line."</p><p><strong>Stem Phase (straight-line acceleration before the break)</strong></p><p>"Maintain full speed through the stem (5–7 yards). Stay vertical with slight forward lean. Eyes stay downfield — do not peek at the QB. Keep defender on your back hip. Stride length is long and powerful. Torso stays square to the sideline."</p><p><strong>Break Phase (the actual 45° cut)</strong></p><p>"Plant hard on the outside foot at exactly 45°. Snap hips violently while keeping shoulders square to the target (no rounding). Head snaps to the QB at the exact moment of the plant. Hands stay tight to the body. Deceleration is sudden and single-step — accelerate INTO the break, don''t slow down before it."</p><p><strong>Catch Phase (ball arrival and after-catch)</strong></p><p>"Eyes track the ball all the way into the hands. Diamond catch position with fingers spread and thumbs together. Secure the ball to the body immediately. Brace core for contact. After catch, explode upfield — no lateral drift. First step after catch should be vertical and decisive."</p>'),
('basics', '<h3><strong>How to Set Up a Training Node</strong></h3><p>Each training node represents a single skill or drill the AI will analyze. Start with a clear, specific name (e.g. "Slant Route", "QB 3-Step Drop", "Vertical Jump").</p><ul><li><strong>Name:</strong> Use the exact skill name athletes and coaches would recognize.</li><li><strong>Icon:</strong> Upload a diagram or icon that visually represents this skill. Appears in the sidebar for quick identification.</li></ul><p>Keep it simple — you can always refine later. The name and icon help you quickly navigate between nodes as your library grows.</p>'),
('videos', '<h3><strong>Adding Elite Reference Videos</strong></h3><p>These videos serve as the gold standard the AI compares athlete uploads against.</p><ul><li>Use high-quality footage of elite athletes performing this exact skill.</li><li>Include multiple angles if possible (sideline + end zone).</li><li>Label each video clearly (e.g. "Davante Adams — Slant vs Man Coverage").</li><li>Prioritize clips where the full movement is visible from start to finish.</li></ul><p>The better your reference videos, the more accurate and specific the AI feedback will be.</p>'),
('overview', '<h3><strong>Writing a Strong Overview</strong></h3><p>The overview is the AI''s context for understanding why this skill matters. Write 2–4 sentences covering:</p><ul><li>What the skill is and when it''s used in game situations.</li><li>Why mastering it matters for athlete development.</li><li>What separates elite execution from average.</li></ul><p><strong>Example:</strong> "The slant route is a quick-breaking inside route used to exploit soft coverage and zone windows. Elite execution requires explosive release, precise 45° break, and immediate acceleration after the catch."</p>'),
('metrics', '<h3><strong>Defining Key Metrics</strong></h3><p>Metrics are the measurable components the AI evaluates. Each metric should be:</p><ul><li><strong>Observable:</strong> Something the AI can detect from video (angles, timing, positions).</li><li><strong>Specific:</strong> Clear unit of measurement and elite target value.</li><li><strong>Weighted:</strong> Assign importance — all weights should total 100%.</li></ul><p><strong>Good metrics:</strong> "Break Angle Accuracy (degrees, target: 45°, weight: 25%)"</p><p><strong>Bad metrics:</strong> "Overall technique" (too vague for AI to measure)</p>'),
('scoring', '<h3><strong>Setting Up Scoring Rules</strong></h3><p>The scoring formula determines how individual metric scores combine into the overall Route Mastery Score (0–100).</p><ul><li>Describe the weighted average formula in plain language.</li><li>Use the weight distribution table to verify all metrics sum to 100%.</li><li>Add bonus rules for exceptional performance (e.g. "+5 if all phases ≥ 80").</li><li>Set confidence thresholds so athletes know when video quality may affect accuracy.</li></ul><p>Use the Scoring Preview Simulator to test different scenarios and verify the formula produces reasonable scores.</p>'),
('errors', '<h3><strong>Documenting Common Errors</strong></h3><p>Help the AI identify and correct typical mistakes athletes make.</p><ul><li><strong>Be specific:</strong> "Rounding the break instead of planting at 45°" not "Bad technique".</li><li><strong>Include the fix:</strong> Every error should have a clear, actionable correction.</li><li>Write in coach voice — direct, encouraging, specific.</li><li>Prioritize the most impactful errors first.</li></ul><p>The AI uses these to give targeted feedback when it detects similar patterns in athlete videos.</p>'),
('phases', '<h3><strong>Defining Phase Breakdowns</strong></h3><p>Phases break the skill into distinct stages for granular analysis.</p><ul><li>Each phase should represent a clearly separable part of the movement.</li><li>Define what success looks like in each phase.</li><li>Include timing cues (e.g. "steps 1–3", "yards 5–7").</li></ul><p>This is different from Mechanics — phases here define the structure, while Mechanics provides the detailed coaching notes for each phase.</p>'),
('reference', '<h3><strong>Reference Objects for Scale</strong></h3><p>The AI needs real-world reference objects to calculate accurate distances and angles from video.</p><ul><li><strong>Best references:</strong> Football (known size), yard lines (known spacing), cones at measured distances.</li><li>Explain how the object should appear in frame.</li><li>Note any calibration steps needed.</li></ul><p>Without a reliable reference object, measurements like "break angle" or "step length" will be estimates rather than precise values.</p>'),
('camera', '<h3><strong>Camera Setup Guidelines</strong></h3><p>Video quality directly impacts AI analysis accuracy. Guide athletes on optimal filming:</p><ul><li><strong>Primary angle:</strong> Sideline view, 10–15 yards back, waist height. Captures full route.</li><li><strong>Secondary angle:</strong> End zone or elevated view for depth perception.</li><li>Ensure the full movement is in frame from start to finish.</li><li>Avoid backlit situations — film with light behind the camera.</li></ul><p>Better video = better analysis. These guidelines help athletes submit videos the AI can actually work with.</p>'),
('checkpoints', '<h3><strong>Setting Form Checkpoints</strong></h3><p>Checkpoints are key moments the AI should analyze closely — the "freeze frames" that matter most.</p><ul><li>Define the exact moment (e.g. "At the plant foot strike during the break").</li><li>Describe what the AI should look for at that moment.</li><li>Order them chronologically through the movement.</li></ul><p><strong>Example:</strong> "Check hip rotation angle at the break point — hips should be rotated 45° toward the target."</p>'),
('prompt', '<h3><strong>Customizing the LLM Prompt</strong></h3><p>The LLM prompt template controls the tone, focus, and structure of AI coach feedback.</p><ul><li>Use template variables like {{athlete_name}}, {{score}}, {{phase_scores}} for dynamic content.</li><li>Set the coaching persona (e.g. "Respond as an NFL position coach").</li><li>Define feedback structure (scores first, then strengths, then improvements).</li><li>Include sport-specific terminology the AI should use.</li></ul><p>Test different prompt styles in the Run Analysis tab to find what produces the most useful feedback.</p>'),
('badges', '<h3><strong>Creating Achievement Badges</strong></h3><p>Badges reward athletes for hitting milestones and keep them motivated.</p><ul><li><strong>Name:</strong> Short, aspirational (e.g. "Route Technician", "Deep Threat").</li><li><strong>Condition:</strong> Clear, measurable unlock criteria (e.g. "Score 85+ on 3 consecutive attempts").</li><li>Mix difficulty levels — some achievable early, some requiring mastery.</li></ul><p>Badges appear on the athlete''s public profile, so make them meaningful and worth showing off.</p>'),
('test', '<h3><strong>Using the Run Analysis Tab</strong></h3><p>Test your node configuration by running analysis on sample videos before making it available to athletes.</p><ul><li>Upload a video or paste a URL of an athlete performing this skill.</li><li>Add a description of what''s happening in the video for context.</li><li>Review the full output: scores, phase breakdown, metrics, and feedback.</li><li>Iterate on your node data (metrics, weights, mechanics notes) based on results.</li></ul><p>Run multiple tests with different skill levels to ensure the scoring feels accurate and the feedback is useful.</p>');
